# Generated by Django 2.2.5 on 2019-10-26 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('PublicId', models.CharField(max_length=64)),
                ('ActivatedOn', models.DateTimeField(default=None)),
                ('ActivatedTill', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PublicId', models.CharField(max_length=64)),
                ('LogoUrl', models.ImageField(upload_to='OrgLogo')),
                ('OrganizationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organization.Organization')),
            ],
        ),
    ]
