# Generated by Django 2.2.5 on 2019-11-02 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('PinCode', models.CharField(max_length=10)),
                ('Country', models.CharField(max_length=50)),
                ('AddressType', models.SmallIntegerField(default=1)),
                ('IsActive', models.BooleanField(default=True)),
                ('OrganizationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organization.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationContactPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('PhoneNumber', models.CharField(max_length=20)),
                ('Designation', models.CharField(max_length=50)),
                ('WorkingFrom', models.DateTimeField(default=None)),
                ('IsActive', models.BooleanField(default=True)),
                ('WorkedTill', models.DateTimeField(default=None)),
                ('OrganizationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organization.Organization')),
                ('PostedAt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organization.OrganizationAddress')),
            ],
        ),
    ]
